### ISSUE TITLE
Blank lines on GSD metadata page in Firefox

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#72] opened 2020-11-24 15:11 UTC
...empty blinking lines between sections English name of the Group and Abstract on GSD metadatad page in **Firefox 83.0 (64-bit, Windows)** 
as reported in https://github.com/CatalogueOfLife/testing/issues/1
@thomasstjerne 

![image](https://user-images.githubusercontent.com/28574252/100112630-111a1b00-2e35-11eb-99d3-d74e47d0f047.png)

**Comment by thomasstjerne** [comment] 2020-11-25 07:06
duplicate of https://github.com/CatalogueOfLife/portal/issues/72

**Closed by thomasstjerne** 2020-11-25 07:06 UTC

**Comment by mdoering** [comment] 2020-11-25 07:57
duplicate of #73 maybe?

**Comment by thomasstjerne** [comment] 2020-11-25 08:48
Its the preflight of https://api.catalogue.life/vocab/rank that fails

**Comment by mdoering** [comment] 2020-11-25 09:00
and why does it fail? It's not even authenticated

**Comment by yroskov** [comment] 2020-11-25 14:12
Firefox for Win 83.0 (64-bit).
Counts are visible now in my browser (fixed):

![image](https://user-images.githubusercontent.com/28574252/100237639-cf50a980-2ef4-11eb-8793-f43f9796d6bd.png)

However, Taxonomic coverage is not visible in my Firefox (it's visible in Chrome). I opened a new ticket: https://github.com/CatalogueOfLife/backend/issues/923

**Comment by mdoering** [comment] 2020-11-25 14:38
maybe some cross browser tests would be nice: https://www.softwaretestinghelp.com/best-cross-browser-testing-tools-to-ease-your-browser-compatibility-testing-efforts/
