### ISSUE TITLE
Add species statistics and estimates to the classification tree

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#12] opened 2020-03-25 16:51 UTC
We need to add species statistics to the classification tree, similar to the legacy interface:

![image](https://user-images.githubusercontent.com/8573609/77562933-a1f7bb80-6e8e-11ea-8277-466924a0ff5d.png)

**Comment by mdoering** [comment] 2020-09-10 14:13
Use `est.sp.` as the estimation label, but also show number of living and extinct species in the CoL.
Partially blocked by https://github.com/CatalogueOfLife/backend/issues/834

**Comment by mdoering** [comment] 2020-09-10 15:17
@olafbanki @thomasstjerne @gdower @yroskov are the actual species counts, not estimates, important for the first release? It will require [backend work](#834) so we need to schedule that

**Comment by yroskov** [comment] 2020-09-10 15:22
How final release will look is important for me, not the first one.

**Comment by mdoering** [comment] 2020-11-14 08:02
duplicate of #23

**Closed by mdoering** 2020-11-14 08:02 UTC
Labels: data
