### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/portal#195] opened 2022-09-28 09:48 UTC
I think it might be useful to state some basic metrics on the COL homepage.
For example number of accepted names, number of synonyms etc. which would be helpful in communicating the growth of content over time. I see checklistbank.org has some.

**Comment by mdoering** [comment] 2022-09-28 10:22
Apart from basic metrics on the homepage it would also be great to have more metrics and some timelines on a new dedicated statistics page. It could start out similar to the CLB metrics one

**Comment by mdoering** [comment] 2024-12-03 15:44
duplicate of https://github.com/CatalogueOfLife/portal/issues/183

**Closed by mdoering** 2024-12-03 15:44 UTC
Labels: enhancement
